@expense_management_app_HostAddress = http://localhost:5089
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhYmMxMjNAZXhhbXBsZS5jb20iLCJqdGkiOiIwMTEzZGM2Yi02NjUzLTQ3MDItYWZmYS02YTRjMWIwM2ZlNzkiLCJleHAiOjE3ODcxOTY5NTIsImlzcyI6IkV4cGVuc2VNYW5hZ2VtZW50QXBpIiwiYXVkIjoiRXhwZW5zZU1hbmFnZW1lbnRDbGllbnQifQ.O_k3MiTWjo6WOt_pvodLjq7ZjUPlbJ7f1i0ekrDeNCE
@refreshToken = 4ku+4czBDjySZ85a+TXSuxRiK7dlkRNODzh/snS9RS6EazMysaTqp1TTtxWrnefh1xO8ZSQ7VlZIbefyJe7IiA==

### Registeration Method Testing
POST {{expense_management_app_HostAddress}}/auth/register
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "SomethingStrong@123"
}

### Login Method Testing
#### A - Correct Credentials
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "SomethingStrong@123"
}

#### B - Wrong Password
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "qwerty"
}

#### C - Incorrect Credentials (both email & password)
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "def@example.com",
    "password": "qwerty"
}

### Refresh Token Rotation Testing
POST {{expense_management_app_HostAddress}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Logout Testing
POST  {{expense_management_app_HostAddress}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Authorization Testing
GET {{expense_management_app_HostAddress}}/auth/me
Authorization: Bearer {{accessToken}}
Accept: application/json

### Testing with Categories.cs & Tags.cs
#### A / Categories.cs
#### Create a Category
POST {{expense_management_app_HostAddress}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "work"
}

#### Retrieve all categories created by the current user
GET {{expense_management_app_HostAddress}}/categories
Authorization: Bearer {{accessToken}}
Accept: application/json 

#### B / Tags.cs
#### Create a Tag
POST {{expense_management_app_HostAddress}}/tags
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "non-essential"
}

#### Retrieve all tags created by the current user
GET {{expense_management_app_HostAddress}}/tags
Authorization: Bearer {{accessToken}}
Accept: application/json

### Testing with ExpenseController.cs
#### Create an expense for the current user
POST {{expense_management_app_HostAddress}}/expenses
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "merchant": "woolworth",
    "amount": 10.00,
    "currency": "aud",
    "expenseDate": "2026-08-10T00:00:00Z",
    "categoryId":null,
    "notes":null,
    "tagIds":[]
}

#### Retrieve all expenses of this current user
GET {{expense_management_app_HostAddress}}/expenses
Authorization: Bearer {{accessToken}}
Accept: application/json

#### Retrieve one expense of this current user based on expenseId
GET {{expense_management_app_HostAddress}}/expenses/10
Authorization: Bearer {{accessToken}}
Accept: application/json

#### Delete one expense of this current user based on expenseId
DELETE {{expense_management_app_HostAddress}}/expenses/1
Authorization: Bearer {{accessToken}}

#### Update one expense of this current user based on expenseId
PUT {{expense_management_app_HostAddress}}/expenses/1
Authorization: Bearer {{accessToken}}
{
    "merchant": "Aldi",
    "amount": 20.00,
    "currency": "usd",
    "expenseDate": "2026-08-13T00:00:00Z",
    "categoryId": 1,
    "notes": "testing",
    "tagIds": [1,2]
}

### Testing with ReceiptsController.cs
#### POST /receipts

##### PDF file
POST {{expense_management_app_HostAddress}}/receipts
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=receiptBoundary

--receiptBoundary
Content-Disposition: form-data; name="file"; filename="sample_file.pdf"
Content-Type: application/pdf

< ../test_files/sample_file.pdf
--receiptBoundary--

##### Upload PNG receipt
POST {{expense_management_app_HostAddress}}/receipts
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=receiptBoundary

--receiptBoundary
Content-Disposition: form-data; name="file"; filename="sample_file.png"
Content-Type: image/png

< ../test_files/sample_file.png
--receiptBoundary--

### Upload JPG receipt
POST {{expense_management_app_HostAddress}}/receipts
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=receiptBoundary

--receiptBoundary
Content-Disposition: form-data; name="file"; filename="sample_file.jpg"
Content-Type: image/jpeg

< ../test_files/sample_file.jpg
--receiptBoundary--

##### JPEG
POST http://localhost:5089/receipts
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=receiptBoundary

--receiptBoundary
Content-Disposition: form-data; name="file"; filename="sample_file.jpeg"
Content-Type: image/jpeg

< ../test_files/sample_file.jpg
--receiptBoundary--

#### GET /receipts
GET {{expense_management_app_HostAddress}}/receipts
Authorization: Bearer {{accessToken}}
Accept: application/json

#### GET /receipts/{receiptId}
GET {{expense_management_app_HostAddress}}/receipts/1
Authorization: Bearer {{accessToken}}
Accept: application/json

#### DELETE /receipts/{receiptId}
DELETE {{expense_management_app_HostAddress}}/receipts/1
Authorization: Bearer {{accessToken}}