@expense_management_app_HostAddress = http://localhost:5089

### Registeration Method Testing
POST {{expense_management_app_HostAddress}}/auth/register
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "SomethingStrong@123"
}

### Login Method Testing
#### A - Correct Credentials
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "SomethingStrong@123"
}

#### B - Wrong Password
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "abc123@example.com",
    "password": "qwerty"
}

#### C - Incorrect Credentials (both email & password)
POST {{expense_management_app_HostAddress}}/auth/login
Content-Type: application/json

{
    "email": "def@example.com",
    "password": "qwerty"
}

### Refresh Token Rotation Testing
POST {{expense_management_app_HostAddress}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "tEvOi+/Xlo8dtM9bpaJOler8n6QZ94b8fb9CWNXeo0yP6A/7Kb/ZeqsQdQfEPt06plftw+QQLXepOS0Hviciag=="

    // Unrevoked RefreshToken:
    // "refreshToken": "cVnd0XdH8HfTnWSdP0OmgSLti0otZclgamgqCCLGRLmj8/hN6Oet2/4/oLn080ExVVjcLMO3UurRW1b0KyaJKA=="
}

### Logout Testing
POST  {{expense_management_app_HostAddress}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "cVnd0XdH8HfTnWSdP0OmgSLti0otZclgamgqCCLGRLmj8/hN6Oet2/4/oLn080ExVVjcLMO3UurRW1b0KyaJKA=="
}

### Authorization Testing
GET {{expense_management_app_HostAddress}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJhYmMxMjNAZXhhbXBsZS5jb20iLCJqdGkiOiIyOTNiNzAyZi0yZWEyLTQ3N2UtOWIxNy1lMjJjMzBjYjI4OTYiLCJleHAiOjE3ODU0ODQzNzQsImlzcyI6IkV4cGVuc2VNYW5hZ2VtZW50QXBpIiwiYXVkIjoiRXhwZW5zZU1hbmFnZW1lbnRDbGllbnQifQ.dqMPKcc2iHdwMJAYMG16_tFyJeQT_YAjEYbkb1HSVbY